In [1]:
import torch
import numpy as np

In [2]:
%matplotlib inline

## Create Tensor

### 1. Tensor from data

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [4]:
# view tensor
x_data

tensor([[1, 2],
        [3, 4]])

### 2. Tensor from numpy array

In [5]:
np_array = np.array(data)
x_data = torch.from_numpy(np_array)

In [6]:
# view tensor
x_data

tensor([[1, 2],
        [3, 4]])

### 3. Tensor from another tensor

In [7]:
x_ones = torch.ones_like(x_data)     # retains the properties of x_data
print(f'Ones Tensor: \n{x_ones}')

Ones Tensor: 
tensor([[1, 1],
        [1, 1]])


In [8]:
x_rand = torch.rand_like(x_data, dtype=torch.float)      # overrides the datatype of x_data
print(f'Random tensor: \n{x_rand}')

Random tensor: 
tensor([[0.2059, 0.7329],
        [0.6138, 0.9472]])


### 4. Tensor with a given shape

In [9]:
shape = (2, 3)
ones_tensor = torch.ones(shape)
rand_tensor = torch.rand(shape)
zeros_tensor = torch.zeros(shape)

In [10]:
# Output:
print(f'Ones Tensor:\n{ones_tensor}')
print(f'Random Tensor:\n{rand_tensor}')
print(f'Zeros Tensor:\n{zeros_tensor}')

Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Random Tensor:
tensor([[0.8495, 0.3925, 0.7415],
        [0.3530, 0.2248, 0.7047]])
Zeros Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Tensor Properties

### Attributes

In [11]:
t = torch.rand(3, 4)
t

tensor([[0.2108, 0.8336, 0.6877, 0.8411],
        [0.5186, 0.6487, 0.2724, 0.4108],
        [0.2202, 0.9537, 0.5341, 0.8642]])

In [13]:
print(f'Shape of tensor: {t.shape}')
print(f'Datatype of tensor: {t.dtype}')
print(f'Device tensor is stored on: {t.device}')

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Operations

Over 100 tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random sampling, and more are comprehensively described here.


#### Standard numpy-like indexing and slicing:

In [14]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

#### Joining tensors 

* to concatenate a sequence of tensors along a given dimension
* For more, visit [torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html)

In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


#### Multiplying tensors

* computes the element-wise product

In [20]:
print(f'torch.mul(tensor): \n{torch.mul(tensor, tensor)}')

# alternative
print(f'tensor*tensor: \n{tensor*tensor}')

torch.mul(tensor): 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor*tensor: 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


* computes the matrix multiplication b/w 2 tensors

In [23]:
print(f'torch.matmul(tensor): \n{torch.matmul(tensor, tensor.T)}')

# alternative
print(f'tensor@tensor: \n{tensor@tensor.T}')

torch.matmul(tensor): 
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor@tensor: 
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


### In-place operations

Operations that have a _ suffix are in-place. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

In [24]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


> In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.

## Bridge with NumPy

### Tensor to NumPy array

In [25]:
t = torch.ones(5)
n = t.numpy()

In [26]:
print(f't: {t}')
print(f'n: {n}')

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [27]:
t.add_(1)     # add 1 to each element & see the change in both tensor & numpy array
print(f't: {t}')
print(f'n: {n}')

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPy array to Tensor

In [28]:
n = np.ones(5)
t = torch.from_numpy(n)

In [29]:
print(f't: {t}')
print(f'n: {n}')

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]


In [30]:
np.add(n, 1, out=n)     # add 1 to each elements of array
print(f't: {t}')
print(f'n: {n}')

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
